### PR TITLE
Parallel instance checks and improved error messages, code cleanup

### LINKED ISSUE #25: Parallelize each instance checking and each check
Title, using goroutines.

### PR DESCRIPTION
**Pull request by Bnyro**
closes #25

### CODE REVIEW

**Comment by FireMasterK** [comment]
It looks like the order of the instances is no longer preserved, as each `getInstanceDetails` call takes a different amount of time each time.

**Comment by Bnyro** [comment]
Makes sense, likely we should just reorder the array of instance after all goroutines are done?

**Comment by FireMasterK** [comment]
I just used a map to store the order along with it, so it works now! (Golang types are really weird too)

**Comment by Bnyro** [comment]
Nice solution! I already had the fear we would need to deal with sorting in go 🫨

**Review by FireMasterK — APPROVED** [review]
Looks good to me, thanks for this!

I tried implementing this a few weeks back but was fighting a lot with wait groups, error channels, and closing them. This implementation is a lot cleaner than what I tried, great work!

**Pull request merged**
